- name: Add masters nodes to masters groups
  hosts: masters
  gather_facts: false
  tags: always
  tasks:
    - name: add nodes to masters group
      group_by:
        key: 'masters'

- name: Add master node to master groups
  hosts: master
  gather_facts: false
  tags: always
  tasks:
    - name: add nodes to masters group
      group_by:
        key: 'master'

- name: Add master-2 node to master-2 groups
  hosts: master-2
  gather_facts: false
  tags: always
  tasks:
    - name: add nodes to masters group
      group_by:
        key: 'master-2'

- name: Add master-3 node to master-3 groups
  hosts: master-3
  gather_facts: false
  tags: always
  tasks:
    - name: add nodes to masters group
      group_by:
        key: 'master-3'

- name: Add o-masters nodes to o-masters groups
  hosts: o-master
  gather_facts: false
  tags: always
  tasks:
    - name: add nodes to masters group
      group_by:
        key: 'o-master'

- name: Add workers nodes to workers groups
  hosts: workers
  gather_facts: false
  tags: always
  tasks:
    - name: add nodes to workers group
      group_by:
        key: 'workers'

