- name: Copy the join command to server location
  command: cp /vagrant/join-command /vagrant/join-command.sh

- name: script executable
  command: chmod 0777 /vagrant/join-command.sh

- name: Join the node to cluster
  command: sh /vagrant/join-command.sh
